---
- name: Crée le fichier d'environnement pour les docker-compose
  ansible.builtin.lineinfile:
    path:  /root/docker/dockercompose/.env
    line: '{{ item }}'
    create: yes
  with_items:
  # Auth 
  - 'TRAEFIK_USER={{ authUser }}'
  - 'TRAEFIK_PASSWORD_HASH={{ authPassword }}'
    # Uptime service
  - 'nextcloudDomaineName={{ nextcloudDomaineName }}'
  - 'portainerDomaineName={{ portainerDomaineName }}'
  - 'traefikDomaineName={{ traefikDomaineName }}'
  - 'uptimeDomaineName={{ uptimeDomaineName }}'
  - 'wordpressDomaineName={{ wordpressDomaineName }}'
  - 'wordpressDomaineName2={{ wordpressDomaineName2 }}'
