version: "3.9"
services:
  freshrss:
    image: freshrss/freshrss
    labels:
      - traefik.http.routers.freshrss.rule=Host(`${freshrssDomaineName}`) # A changer entre sous domaine !
      - traefik.http.routers.freshrss.entrypoints=https
      - traefik.http.routers.freshrss.tls=true
      - traefik.http.routers.freshrss.tls.certresolver=${CERT_RESOLVER}
      #- traefik.http.services.freshrss.loadbalancer.server.port=8200 # Port 80 pas besoin
    volumes:
      - /apps/freshRss/:/var/www/FreshRSS/data
    
    restart: unless-stopped
    networks:
      - proxy


networks:
  proxy:
    external: true