version: "2"
services:
  # Base de données
  matomo-db:
    image: linuxserver/mariadb
    container_name: matomo-db
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=pihvzlbkcgvlknfze!ef6e4
      - TZ=Europe/Paris
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=Matomo65468431
      # Flag necessary for the database max allowed packet check
      # https://matomo.org/faq/troubleshooting/faq_183/
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - /apps/web/matomo/db:/config
    networks: 
      - proxy


  # Matomo : https://fr.matomo.org
  matomo:
    image: matomo
    container_name: matomo
    restart: unless-stopped
    environment:
      - MATOMO_DATABASE_HOST=matomo-db
      - MATOMO_DATABASE_DBNAME=matomo
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=Matomo65468431
    labels:
      - traefik.http.routers.matomo.rule=Host(`${matomoDomaineName}`) # A changer entre sous domaine !
      - traefik.http.routers.matomo.entrypoints=https
      - traefik.http.routers.matomo.tls=true
      - traefik.http.routers.matomo.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.services.matomo.loadbalancer.server.port=80

    volumes:
      - /apps/web/matomo/data:/var/www/html
    depends_on:
      - matomo-db
    networks: 
      - proxy                

networks:
  proxy:
    external:
      name: proxy
