version: "3.9"
services:
  openproject:
    image: openproject/community:12
    labels:
      - traefik.http.routers.openproject.rule=Host(`${openprojectDomaineName}`) # A changer entre sous domaine !
      - traefik.http.routers.openproject.entrypoints=https
      - traefik.http.routers.openproject.tls=true
      - traefik.http.routers.openproject.tls.certresolver=${CERT_RESOLVER}
    volumes:
      - /apps/openproject/pgdata/:/var/openproject/pgdata
      - /apps/openproject/assets/:/var/openproject/asset
    
    restart: always

    networks:
      - proxy


networks:
  proxy:
    external: true