version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce
    labels:
      - traefik.http.routers.portainer.rule=Host(`${portainerDomaineName}`) # A changer entre sous domaine !
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.services.portainer.loadbalancer.server.port=9000 # Port que traefik du containeur
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /apps/monitoring/portainer/:/data
    
    restart: always

    networks:
      - proxy


networks:
  proxy:
    external: true

