version: "3.9"
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    labels:
      - traefik.http.routers.uptime.rule=Host(`${uptimeDomaineName}`) # A changer entre sous domaine !
      - traefik.http.routers.uptime.entrypoints=http
      - traefik.http.services.uptime.loadbalancer.server.port=3001 # Port que traefik du containeur
    volumes:
      - /apps/monitoring/uptime/:/app/data

    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true