---
# defaults file for lauchCompose


# AUTH - htpasswd -b -c ~/temp/password admin test101
authUser: alex
authPassword: $2y$05$2CngjDo0TQ5oMDawqafOo.MTSCLteZBNhy7BJSvd5XtdBSnBNpK8O

# SERVICES
# uptimeActive: 'yes'  ou uptimeActive: 'no'
# uptimeDomaineName: uptime2.onlymore.net
# uptimeAuth: 'yes' ou uptimeAuth: 'no'

serviceVps:
  traefik: traefik
  nextcloud: nextcloud
  portainer: portainer
  uptime: uptime
  wordpress: wordpress



# nextcloud
nextcloudActive: 'yes' # Lancer le docker compose ou non : 
nextcloudDomaineName: cloud.boulard.sio
nextcloudAuth: 'no'

# portainer
portainerActive: 'yes' 
portainerDomaineName: portainer.boulard.sio
portainerAuth: 'no'


# traefik
traefikActive: 'yes' 
traefikDomaineName: traefik.boulard.sio
traefikAuth: 'yes'

# Uptime
uptimeActive: 'yes' # Lancer le docker compose ou non : 
uptimeDomaineName: uptime.boulard.sio
uptimeAuth: 'no'

# wordpress
wordpressActive: 'yes' # Lancer le docker compose ou non : 
wordpressDomaineName: web.boulard.sio
wordpressDomaineName2: web2.boulard.sio
wordpressAuth: 'no'

